development:
  adapter: postgresql
  encoding: unicode
  database: MyHomeBank_development
  pool: 5
  username: Awan
  password:

      test:
        adapter: postgresql
        encoding: unicode
        database: MyHomeBank_test
        pool: 5
        username: Awan
        password:

      production:
        adapter: postgresql
        encoding: unicode
        database: MyHomeBank_production
        pool: 5
        username: MyHomeBank
        password: